/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Descendants</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Descendants#getGroup <em>Group</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Descendants#getDimension <em>Dimension</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDescendants()
 * @model
 * @generated
 */
public interface Descendants extends ReportQueryParameters
{
  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Group</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDescendants_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Descendants#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Dimension</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dimension</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimension</em>' containment reference.
   * @see #setDimension(Reference)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDescendants_Dimension()
   * @model containment="true"
   * @generated
   */
  Reference getDimension();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Descendants#getDimension <em>Dimension</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dimension</em>' containment reference.
   * @see #getDimension()
   * @generated
   */
  void setDimension(Reference value);

} // Descendants
