/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import essbase_model.Group;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.GroupDeclaration#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGroupDeclaration()
 * @model
 * @generated
 */
public interface GroupDeclaration extends Declaration
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(Group)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGroupDeclaration_Value()
   * @model
   * @generated
   */
  Group getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.GroupDeclaration#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Group value);

} // GroupDeclaration
