/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMemberDeclaration()
 * @model
 * @generated
 */
public interface MemberDeclaration extends Declaration
{
} // MemberDeclaration
