/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query MDX</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.QueryMDX#getR <em>R</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.QueryMDX#getFr <em>Fr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.QueryMDX#getC <em>C</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.QueryMDX#getFc <em>Fc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryMDX()
 * @model
 * @generated
 */
public interface QueryMDX extends Query
{
  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference.
   * @see #setR(MDXRows)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryMDX_R()
   * @model containment="true"
   * @generated
   */
  MDXRows getR();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.QueryMDX#getR <em>R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' containment reference.
   * @see #getR()
   * @generated
   */
  void setR(MDXRows value);

  /**
   * Returns the value of the '<em><b>Fr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fr</em>' containment reference.
   * @see #setFr(MDXFunction)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryMDX_Fr()
   * @model containment="true"
   * @generated
   */
  MDXFunction getFr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.QueryMDX#getFr <em>Fr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fr</em>' containment reference.
   * @see #getFr()
   * @generated
   */
  void setFr(MDXFunction value);

  /**
   * Returns the value of the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' containment reference.
   * @see #setC(MDXCOlumns)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryMDX_C()
   * @model containment="true"
   * @generated
   */
  MDXCOlumns getC();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.QueryMDX#getC <em>C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' containment reference.
   * @see #getC()
   * @generated
   */
  void setC(MDXCOlumns value);

  /**
   * Returns the value of the '<em><b>Fc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fc</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fc</em>' containment reference.
   * @see #setFc(MDXFunction)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryMDX_Fc()
   * @model containment="true"
   * @generated
   */
  MDXFunction getFc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.QueryMDX#getFc <em>Fc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fc</em>' containment reference.
   * @see #getFc()
   * @generated
   */
  void setFc(MDXFunction value);

} // QueryMDX
