/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Report</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.QueryReport#getQueryReport <em>Query Report</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryReport()
 * @model
 * @generated
 */
public interface QueryReport extends Query
{
  /**
   * Returns the value of the '<em><b>Query Report</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ReportQueryParameters}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Query Report</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query Report</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getQueryReport_QueryReport()
   * @model containment="true"
   * @generated
   */
  EList<ReportQueryParameters> getQueryReport();

} // QueryReport
