/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Report</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Report#getRepout <em>Repout</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReport()
 * @model
 * @generated
 */
public interface Report extends Statement
{
  /**
   * Returns the value of the '<em><b>Repout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Repout</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repout</em>' containment reference.
   * @see #setRepout(StringReference)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReport_Repout()
   * @model containment="true"
   * @generated
   */
  StringReference getRepout();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Report#getRepout <em>Repout</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repout</em>' containment reference.
   * @see #getRepout()
   * @generated
   */
  void setRepout(StringReference value);

} // Report
