/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Report Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ReportParameter#getReparam <em>Reparam</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReportParameter()
 * @model
 * @generated
 */
public interface ReportParameter extends ReportQueryParameters
{
  /**
   * Returns the value of the '<em><b>Reparam</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reparam</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reparam</em>' containment reference.
   * @see #setReparam(StringReference)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReportParameter_Reparam()
   * @model containment="true"
   * @generated
   */
  StringReference getReparam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ReportParameter#getReparam <em>Reparam</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reparam</em>' containment reference.
   * @see #getReparam()
   * @generated
   */
  void setReparam(StringReference value);

} // ReportParameter
