/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.ReportQueryParameters;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Report Query Parameters</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReportQueryParametersImpl extends MinimalEObjectImpl.Container implements ReportQueryParameters
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReportQueryParametersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.REPORT_QUERY_PARAMETERS;
  }

} //ReportQueryParametersImpl
